name: mats_socket
description: Client library for MatsSocket server.

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  web_socket_channel: 1.1.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  mockito: 4.1.1
  logging: 0.11.3+2
